import { z } from "zod";

export const updateSettingsSchema = z.object({
  eventsEnabled: z.boolean().optional(),
  heroEventEnabled: z.boolean().optional(),
  aboutTitle: z.string().min(1, "El título es requerido").max(200).optional(),
  aboutSubtitle: z.string().min(1, "El subtítulo es requerido").max(500).optional(),
  aboutParagraph1: z.string().min(1, "Este campo es requerido").max(2000).optional(),
  aboutParagraph2: z.string().min(1, "Este campo es requerido").max(2000).optional(),
  aboutQuote: z.string().min(1, "La cita es requerida").max(500).optional(),
  aboutQuoteAuthor: z.string().min(1, "El autor es requerido").max(100).optional(),
  yearFounded: z.number().int().min(1900).max(new Date().getFullYear()).optional(),
  value1Title: z.string().min(1, "El título es requerido").max(100).optional(),
  value1Description: z.string().min(1, "La descripción es requerida").max(200).optional(),
  value2Title: z.string().min(1, "El título es requerido").max(100).optional(),
  value2Description: z.string().min(1, "La descripción es requerida").max(200).optional(),
  value3Title: z.string().min(1, "El título es requerido").max(100).optional(),
  value3Description: z.string().min(1, "La descripción es requerida").max(200).optional(),
  addressStreet: z.string().min(1, "La dirección es requerida").max(200).optional(),
  addressCity: z.string().min(1, "La ciudad es requerida").max(100).optional(),
  addressPostalCode: z.string().min(1, "El código postal es requerido").max(10).optional(),
  instagramHandle: z.string().min(1, "El usuario de Instagram es requerido").max(50).optional(),
  heroTitle: z.string().min(1, "El título es requerido").max(200).optional(),
  heroSubtitle: z.string().min(1, "El subtítulo es requerido").max(500).optional(),
  heroTagline: z.string().max(500).optional().nullable(),
  heroMarquee: z.string().max(200).optional().nullable(),
  heroImage1: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  heroImage2: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  aboutImage1: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  aboutImage2: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  aboutImage3: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  contactImage: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  glovoUrl: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  uberEatsUrl: z.string().url("URL inválida").optional().nullable().or(z.literal("")),
  phone: z.string().max(30).optional().nullable(),
  footerTagline: z.string().max(300).optional().nullable(),
  footerEstLabel: z.string().max(100).optional().nullable(),
  heroBadge: z.string().max(100).optional().nullable(),
  heroCtaText: z.string().max(50).optional().nullable(),
  heroDeliveryLabel: z.string().max(50).optional().nullable(),
  heroKitchenLabel: z.string().max(50).optional().nullable(),
  aboutHeroTitle: z.string().max(100).optional().nullable(),
  aboutValuesTitle: z.string().max(100).optional().nullable(),
  contactSectionTitle: z.string().max(100).optional().nullable(),
  contactPhoneLabel: z.string().max(50).optional().nullable(),
  contactSocialLabel: z.string().max(50).optional().nullable(),
  eventsOrgTitle: z.string().max(100).optional().nullable(),
  eventsOrgDesc: z.string().max(500).optional().nullable(),
  eventsOrgCta: z.string().max(50).optional().nullable(),
  schedule: z.string().optional(),
});

export type UpdateSettingsInput = z.infer<typeof updateSettingsSchema>;
